### ISSUE TITLE
canvasの枚数、確保について。

### ISSUE THREAD

**Issue by miyokichi** [Gugen-MagicHand/MagicHand#3]
本番用プログラムでのcanvasの枚数って、何枚？
あと、その確保ってグローバル？それとも、canvasにトラックボール の軌跡を書くクラスで確保する？

**Comment by miyokichi** [comment]
あと、キューに渡すのはcanvasのポインタでおけ

**Comment by miyokichi** [comment]
操作ミスった。
キューに渡すのはcanvasのポインタでいい？

**Comment by ContentsViewer** [comment]
キュー上にあるキャンバスに直接操作したほうがいいかも。
ポインタを渡すとメモリの確保と解放をキューの出し入れ時に行うことになって、メモリの断片化が起こる可能性がある。

キャンバスの枚数は10枚かな。
8x8だから、メモリもそれほど食わない

**Comment by ContentsViewer** [comment]
あと、キューはグローバルにおきたい

**Comment by miyokichi** [comment]
キューにあらかじめcanvasをpushしておいて、それを参照するってこと？
じゃあ、そのcanvasもグローバルやんな？

**Comment by ContentsViewer** [comment]
まあそうやな。
キューはこのキャンバスが空いてますよとか、
先に入れたのはこのキャンバスですとかを教える

**Comment by miyokichi** [comment]
了解。

**Comment by miyokichi** [comment]
ソーリー。もう一つ。
queueのキャンバスを直接編集するんじゃなくて、
ScaleTo関数ができてるから、トラックボールの軌跡を描くクラスで一枚canvas確保して、それをqueueにコピーするって感じでいいよな？

**Comment by ContentsViewer** [comment]
そうやな.ちなみに部室来る?

**Comment by miyokichi** [comment]
いく。あと、どうでもいいけど、ReadPixelがReadPixcelになってる。
canvasもライブラリフォルダにほりこんでほしい。

**Comment by ContentsViewer** [comment]
ほんまや.了解
